mail.host=stmp.gmail.com
mail.port=587
mail.sender=mihailnadia27@gmail.com
mail.password=akgpstrbjkvcoqxa
mail.properties.mail.smtp.auth=true
mail.properties.mail.smtp.starttls.enable=true
mail.massage=hello, a new ticket has been created
mail.sendTo=mikhaily0@mail.ru,wewerwerrr53@gmail.com

