spring.mail.host=stmp.gmail.com
spring.mail.port=587
spring.mail.username=mihailnadia27@gmail.com
spring.mail.password=akgpstrbjkvcoqxa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

